# Generated by Django 2.2.5 on 2019-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
