# Generated by Django 2.2.5 on 2019-09-28 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=datetime.datetime(2019, 9, 28, 12, 29, 53, 598052, tzinfo=utc), max_length=25),
            preserve_default=False,
        ),
    ]
